# Change these first
owner: AlexGuada # GitHub username
repo: upptime # GitHub repository

sites:
  - name: AXG-DE1
    url: $AXG_DE1
    icon: https://alessio-guadagno.it/favicon.ico
  - name: AXG-FR1 (TS)
    url: $AXG_FR1
    icon: https://alessio-guadagno.it/favicon.ico
  - name: AXG-UK1
    url: $AXG_UK1
    icon: https://alessio-guadagno.it/favicon.ico


status-website:
  name: AXG Network
  cname: sts.alessio-guadagno.it
  theme: dark
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  favicon: https://alessio-guadagno.it/favicon.ico
  introTitle: "**AXG Netowrk Status** powered by [Upptime](https://github.com/upptime/upptime)"
  #introMessage:
  #navbar:
    #- title: Status
      #href: /
    #- title: GitHub
      #href: https://github.com/$OWNER/$REPO 
