# Change these first
owner: AlexGuada # GitHub username
repo: upptime # GitHub repository

sites:
  - name: AXG-DE1
    url: $AXG_DE1
    icon: $ICO
  - name: AXG-FR1 (TS)
    url: $AXG_FR1
    icon: $ICO
  - name: AXG-UK1
    url: $AXG_UK1
    icon: $ICO


status-website:
  cname: sts.alessio-guadagno.it
  theme: dark
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AXG Network
  introTitle: "**AXG Netowrk Status** powered by [Upptime](https://github.com/upptime/upptime)"
  #introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO 
